AWSTemplateFormatVersion: 2010-09-09
Description: Creates the DynamoDB and S3 structure of the Accelerated Query Pack.
Parameters:
  # Prefix used for S3 Buckets and DynamomDB tables (so devo, gamma, prod etc can share account)
  EnvironmentPrefix:
    Type: String
    Description: Enter an environment prefix for the S3 Buckets and DynamoDB tables ([a-z][a-z0-9]+)
    MinLength: 3
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"
    
  ProjectName:
    Type: String
    Description: Enter an name for the project which is used for the S3 Buckets and DynamoDB tables ([a-z][a-z0-9]+)
    MinLength: 3
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"
  
  ProjectNamePrefix:
    Type: String
    Description: Enter an additional prefix to be appended before the project name to ensure the uniqueness of the S3 Buckets ([a-z][a-z0-9]+)
    MinLength: 2
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"

  KMSKeyARN:
    Type: String
    Description: Enter a KMS Key ARN for the S3 bucket encryption (no encryption is applied if this field is blank).

  S3CurationName:
    Type: String
    Default: curation
    Description: Enter a name for the curation bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"

  S3FailedCurationName:
    Type: String
    Default: failed-curation
    Description: Enter a name for the S3 failed curation bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"
  
  S3ScriptsName:
    Type: String
    Default: scripts
    Description: Enter the name of the S3 scrips bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"
  
  S3LogsName:
    Type: String
    Default: curation-logs
    Description: Enter the name of the S3 logs bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"

  CurationDetailsTableName:
    Type: String
    Default: curationDetails
    Description: Enter the Curation Details DynamoDB table name.
  CurationHistoryTableName:
    Type: String
    Default: curationHistory
    Description: Enter the Curation History DynamoDB table name.

Conditions:
  HasKMSKey:
    !Not [!Equals [!Ref KMSKeyARN, ""]]

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Environment Prefix
        Parameters:
          - EnvironmentPrefix
      - Label:
          default: Project Name
        Parameters:
          - ProjectName
          - ProjectNamePrefix
      - Label:
          default: S3 Data Buckets
        Parameters:
          - S3CurationName
          - S3FailedCurationName
          - S3LogsName
          - S3ScriptsName
      - Label:
          default: KMS Keys
        Parameters:
          - KMSKeyARN
      - Label:
          default: Curation DynamoDB Table
        Parameters:
          - CurationDetailsTableName
          - CurationHistoryTableName
    
Resources:
  # DynamoDB Tables
  CurationDetailsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "curationType"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "curationType"
          KeyType: "HASH"
      SSESpecification:
          SSEEnabled: true
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      TableName: !Sub '${EnvironmentPrefix}${CurationDetailsTableName}'
      BillingMode: PAY_PER_REQUEST      
  CurationHistoryTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "curationType"
          AttributeType: "S"
        -
          AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "curationType"
          KeyType: "HASH"
        -
          AttributeName: "timestamp"
          KeyType: "RANGE"
      SSESpecification:
          SSEEnabled: true
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      TableName: !Sub '${EnvironmentPrefix}${CurationHistoryTableName}'
      BillingMode: PAY_PER_REQUEST      
  # S3 Buckets  
  AcceleratedQueryCodePackages:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-acceleratedquerycodepackages"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true            
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
          
  S3Logs:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: "LogDeliveryWrite"
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3LogsName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true              
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]

      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
  
  S3Scripts:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3ScriptsName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true   
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      LoggingConfiguration:
        DestinationBucketName: !Ref S3Logs
        LogFilePrefix:
          !Sub "${S3ScriptsName}/"
     
  S3Curation:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3CurationName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true   
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      LoggingConfiguration:
        DestinationBucketName: !Ref S3Logs
        LogFilePrefix:
          !Sub "${S3CurationName}/"
          
  S3FailedCuration:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3FailedCurationName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true              
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      LoggingConfiguration:
        DestinationBucketName: !Ref S3Logs
        LogFilePrefix:
          !Sub "${S3FailedCurationName}/"

Outputs:
  CurationDetailsTableName:
    Description: The name of the Curation Details DDBTable
    Value: !Ref CurationDetailsTable
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationDetailsTableName"   
  CurationHistoryTableName:
    Description: The name of the Curation History DDBTable
    Value: !Ref CurationHistoryTable
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationHistoryTableName"          
  S3CuratedName:
    Description: The name of the Curation S3 bucket created
    Value: !Ref S3Curation
    Export: 
      Name: !Sub "${EnvironmentPrefix}-S3Curation-Name"
  S3ScriptsName:
    Description: The name of the scripts S3 bucket created
    Value: !Ref S3Scripts
    Export: 
      Name: !Sub "${EnvironmentPrefix}-S3Scripts-Name"
  S3FailedCuratedName:
    Description: The name of the Failed Curation S3 bucket created
    Value: !Ref S3FailedCuration
    Export: 
      Name: !Sub "${EnvironmentPrefix}-S3FailedCuration-Name"
