AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates the Query Pack component of the Data Lake.
Parameters:
  EnvironmentPrefix:
    Type: String
    Description: Enter the environment prefix used for the DataLake structure (S3
      Buckets and DynamoDB tables
    MinLength: 3
    MaxLength: 19
    AllowedPattern: '[a-z][a-z0-9-]+'
Resources:
  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: '*'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${EnvironmentPrefix}-accelerated-query-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: S3GetPutTag
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:HeadObject
            - s3:ListAllMyBuckets
            - s3:GetBucketLocation
            - s3:ListBucketMultipartUploads
            - s3:ListMultipartUploadParts
            - s3:AbortMultipartUpload
            - s3:ListBucket
            - s3:GetObjectVersionTagging
            - s3:GetObjectTagging
            - s3:PutObjectTagging
            - s3:PutObjectAcl
            Resource: '*'
      - PolicyName: KMSBasic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - kms:Decrypt
            - kms:Encrypt
            - kms:PutKeyPolicy
            - kms:GenerateDataKey
            Resource: '*'
      - PolicyName: Logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: '*'
      - PolicyName: Glue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - glue:GetDatabase
            - glue:GetTable
            - glue:GetPartition
            - glue:GetPartitions
            Resource: '*'
      - PolicyName: DDBGetPutScan
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchWriteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:GetShardIterator
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DescribeStream
            - dynamodb:UpdateTable
            - dynamodb:GetRecords
            Resource: '*'
      - PolicyName: AthenaAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - athena:GetQueryExecution
            - athena:GetQueryResults
            - athena:ListQueryExecutions
            - athena:StartQueryExecution
            Resource: '*'
      - PolicyName: CodeCommit
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - codecommit:GetBlob
            - codecommit:GetFile
            - codecommit:GetFolder
            - codecommit:GetRepository
            - codecommit:ListRepositories
            Resource: '*'
      - PolicyName: EventBridge
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:DeleteRule
            - events:DescribeRule
            - events:PutRule
            - events:PutTargets
            Resource: '*'
  CurationDetailsStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn:
        Fn::ImportValue:
          Fn::Sub: ${EnvironmentPrefix}-CurationDetailsStreamARN
      FunctionName:
        Fn::GetAtt:
        - CreateNewEventRule
        - Arn
      StartingPosition: LATEST
    DependsOn: LambdaExecutionRole
  CreateNewEventRule:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-create-new-event-rule
      Handler: createNewEventRule.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/912bf16ed3f2a7a8601b5a772f883594
      Description: Create a new event rule using the cron expression.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
  StartCurationProcessing:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-start-curation-processing
      Handler: startCurationProcessing.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/84b1cf932e507f23a9415fdf44eaf04c
      Description: Initiates the Query Processing Step Function.
      MemorySize: 128
      Timeout: 300
      Policies:
      - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationHistoryTableName
      Environment:
        Variables:
          CURATION_DETAILS_TABLE_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
          CURATION_HISTORY_TABLE_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationHistoryTableName
          STEP_FUNCTION:
            Ref: QueryProcessor
          CURATION_BUCKET_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-S3Curation-Name
          SCRIPTS_REPO_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CodeCommitScriptsRepo-Name
  RetrieveDetails:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-retrieve-details
      Handler: retrieveDetails.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/5b9e5b8e86228185aea64874c3ad0f94
      Description: Retrieves the details from the curation details dynamodb table.
      MemorySize: 128
      Timeout: 300
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
  ValidateDetails:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-validate-details
      Handler: validateDetails.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/2a19a8f8998fce90db56bad7aec59112
      Description: Validates details that are within the dynamodb entry.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
  StartQueryExecution:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-start-query-execution
      Handler: startQueryExecution.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/e46183469fbf2a520adc9352c8e88ef8
      Description: Starts the query using the details from the dynamodb item.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
  GetQueryExecutionStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-get-query-execution-status
      Handler: getQueryExecutionStatus.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/b47c0ecc4e720b51e4d127e4090d1687
      Description: Retrieves the status of the execution and the output location.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
  UpdateOutputDetails:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-update-output-details
      Handler: updateOutputDetails.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/5e97f771bc55e8b652431cd40ec34e47
      Description: Update the output file with details defined in the dynamodb item
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
  QueryProcessor:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName:
        Fn::Sub: ${EnvironmentPrefix}queryengine
      DefinitionString:
        Fn::Sub:
        - "{\n  \"Comment\": \"State machine to query data available in the data lake\"\
          ,\n  \"StartAt\": \"RetrieveDetails\",\n  \"States\": {\n    \"RetrieveDetails\"\
          : {\n      \"Type\": \"Task\",\n      \"Resource\": \"${RetrieveDetailsArn}\"\
          ,\n      \"Comment\": \"Retrieves the details that are within the dynamodb\
          \ entry.\",\n      \"Next\": \"ValidateDetails\",\n      \"Catch\": [\n\
          \        {\n          \"ErrorEquals\": [\"RetrieveCurationDetailsException\"\
          ,\"Exception\"],\n          \"ResultPath\": \"$.error-info\",\n        \
          \  \"Next\": \"FinishedProcessingUnsuccessfulFile\"\n        }\n      ],\n\
          \      \"Retry\" : [\n        {\n          \"ErrorEquals\": [\n        \
          \    \"Lambda.Unknown\",\n            \"Lambda.ServiceException\",\n   \
          \         \"Lambda.AWSLambdaException\",\n            \"Lambda.SdkClientException\"\
          \n          ],\n          \"IntervalSeconds\": 2,\n          \"MaxAttempts\"\
          : 4,\n          \"BackoffRate\": 1.5\n        },\n        {\n          \"\
          ErrorEquals\": [\n            \"States.ALL\"\n          ],\n          \"\
          IntervalSeconds\": 2,\n          \"MaxAttempts\": 4,\n          \"BackoffRate\"\
          : 1.5\n        }\n      ]\n    },\n\n    \"ValidateDetails\": {\n      \"\
          Type\": \"Task\",\n      \"Resource\": \"${ValidateDetailsArn}\",\n    \
          \  \"Comment\": \"Validates the details that are within the dynamodb entry.\"\
          ,\n      \"Next\": \"StartQueryExecution\",\n      \"Catch\": [\n      \
          \  {\n          \"ErrorEquals\": [\"ValidateDetailsException\",\"Exception\"\
          ],\n          \"ResultPath\": \"$.error-info\",\n          \"Next\": \"\
          FinishedProcessingUnsuccessfulFile\"\n        }\n      ],\n      \"Retry\"\
          \ : [\n        {\n          \"ErrorEquals\": [\n            \"Lambda.Unknown\"\
          ,\n            \"Lambda.ServiceException\",\n            \"Lambda.AWSLambdaException\"\
          ,\n            \"Lambda.SdkClientException\"\n          ],\n          \"\
          IntervalSeconds\": 2,\n          \"MaxAttempts\": 4,\n          \"BackoffRate\"\
          : 1.5\n        },\n        {\n          \"ErrorEquals\": [\n           \
          \ \"States.ALL\"\n          ],\n          \"IntervalSeconds\": 2,\n    \
          \      \"MaxAttempts\": 4,\n          \"BackoffRate\": 1.5\n        }\n\
          \      ]\n    }, \n\n    \"StartQueryExecution\": {\n      \"Type\": \"\
          Task\",\n      \"Resource\": \"${StartQueryExecutionArn}\",\n      \"Comment\"\
          : \"Starts the query using the details from the dynamodb item.\",\n    \
          \  \"Next\": \"Wait\",\n      \"Catch\": [\n        {\n          \"ErrorEquals\"\
          : [\"StartQueryExecutionException\",\"Exception\"],\n          \"ResultPath\"\
          : \"$.error-info\",\n          \"Next\": \"FinishedProcessingUnsuccessfulFile\"\
          \n        }\n      ],\n      \"Retry\" : [\n          {\n            \"\
          ErrorEquals\": [\n              \"Lambda.Unknown\",\n              \"Lambda.ServiceException\"\
          ,\n              \"Lambda.AWSLambdaException\",\n              \"Lambda.SdkClientException\"\
          \n            ],\n            \"IntervalSeconds\": 2,\n            \"MaxAttempts\"\
          : 4,\n            \"BackoffRate\": 1.5\n          },\n          {\n    \
          \        \"ErrorEquals\": [\n              \"States.ALL\"\n            ],\n\
          \            \"IntervalSeconds\": 2,\n            \"MaxAttempts\": 4,\n\
          \            \"BackoffRate\": 1.5\n          }\n      ]\n    }, \n\n   \
          \ \"Wait\": {\n      \"Type\": \"Wait\",\n      \"Seconds\": 15,\n     \
          \ \"Next\": \"GetQueryExecutionStatus\"\n    },\n    \n    \"GetQueryExecutionStatus\"\
          : {\n      \"Type\": \"Task\",\n      \"Resource\": \"${GetQueryExecutionStatusArn}\"\
          ,\n      \"Comment\": \"Retrieves the status of the execution and the output\
          \ location.\",\n      \"Next\": \"HandleStatus\",\n      \"Catch\": [\n\
          \        {\n          \"ErrorEquals\": [\"StartQueryExecutionException\"\
          ,\"Exception\"],\n          \"ResultPath\": \"$.error-info\",\n        \
          \  \"Next\": \"FinishedProcessingUnsuccessfulFile\"\n        }\n      ],\n\
          \      \"Retry\" : [\n        {\n          \"ErrorEquals\": [\n        \
          \    \"Lambda.Unknown\",\n            \"Lambda.ServiceException\",\n   \
          \         \"Lambda.AWSLambdaException\",\n            \"Lambda.SdkClientException\"\
          \n          ],\n          \"IntervalSeconds\": 2,\n          \"MaxAttempts\"\
          : 4,\n          \"BackoffRate\": 1.5\n        },\n        {\n          \"\
          ErrorEquals\": [\n            \"States.ALL\"\n          ],\n          \"\
          IntervalSeconds\": 2,\n          \"MaxAttempts\": 4,\n          \"BackoffRate\"\
          : 1.5\n        }\n      ]\n    }, \n \n    \"HandleStatus\": {\n      \"\
          Type\": \"Choice\",\n      \"Choices\": [\n        {\n          \"Variable\"\
          : \"$.queryStatus\",\n          \"StringEquals\": \"SUCCEEDED\",\n     \
          \     \"Next\": \"UpdateOutputDetails\"\n        },\n        {\n       \
          \   \"Variable\": \"$.queryStatus\",\n          \"StringEquals\": \"FAILED\"\
          ,\n          \"Next\": \"FinishedProcessingUnsuccessfulFile\"\n        }\n\
          \      ],\n      \"Default\": \"GetQueryExecutionStatus\"\n    },  \n  \
          \  \"UpdateOutputDetails\": {\n      \"Type\": \"Task\",\n      \"Resource\"\
          : \"${UpdateOutputDetailsArn}\",\n      \"Comment\": \"Update the output\
          \ file with details defined in the dynamodb item.\",\n      \"Next\": \"\
          FinishedProcessingSuccessfulFile\",\n      \"Catch\": [\n        {\n   \
          \       \"ErrorEquals\": [\"StartQueryExecutionException\",\"Exception\"\
          ],\n          \"ResultPath\": \"$.error-info\",\n          \"Next\": \"\
          FinishedProcessingUnsuccessfulFile\"\n        }\n      ],\n      \"Retry\"\
          \ : [\n        {\n          \"ErrorEquals\": [\n            \"Lambda.Unknown\"\
          ,\n            \"Lambda.ServiceException\",\n            \"Lambda.AWSLambdaException\"\
          ,\n            \"Lambda.SdkClientException\"\n          ],\n          \"\
          IntervalSeconds\": 2,\n          \"MaxAttempts\": 4,\n          \"BackoffRate\"\
          : 1.5\n        },\n        {\n          \"ErrorEquals\": [\n           \
          \ \"States.ALL\"\n          ],\n          \"IntervalSeconds\": 2,\n    \
          \      \"MaxAttempts\": 4,\n          \"BackoffRate\": 1.5\n        }\n\
          \      ]\n    },\n\n    \"FinishedProcessingUnsuccessfulFile\": {\n    \
          \  \"Type\": \"Pass\",\n      \"Result\": \"Fail\",\n      \"End\": true\n\
          \    },\n\n    \"FinishedProcessingSuccessfulFile\": {\n      \"Type\":\
          \ \"Pass\",\n      \"Result\": \"Success\",\n      \"End\": true\n    }\n\
          \  }\n}"
        - RetrieveDetailsArn:
            Fn::GetAtt:
            - RetrieveDetails
            - Arn
          ValidateDetailsArn:
            Fn::GetAtt:
            - ValidateDetails
            - Arn
          StartQueryExecutionArn:
            Fn::GetAtt:
            - StartQueryExecution
            - Arn
          GetQueryExecutionStatusArn:
            Fn::GetAtt:
            - GetQueryExecutionStatus
            - Arn
          UpdateOutputDetailsArn:
            Fn::GetAtt:
            - UpdateOutputDetails
            - Arn
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
