AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates the Query Pack component of the Data Lake.
Parameters:
  EnvironmentPrefix:
    Type: String
    Description: Enter the environment prefix used for the DataLake structure (S3
      Buckets and DynamoDB tables
    MinLength: 3
    MaxLength: 19
    AllowedPattern: '[a-z][a-z0-9-]+'
Resources:
  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: '*'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${EnvironmentPrefix}-accelerated-query-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: S3GetPutTag
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:HeadObject
            - s3:GetObjectVersionTagging
            - s3:GetObjectTagging
            - s3:PutObjectTagging
            - s3:PutObjectAcl
            Resource: '*'
      - PolicyName: KMSBasic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - kms:Decrypt
            - kms:Encrypt
            - kms:PutKeyPolicy
            - kms:GenerateDataKey
            Resource: '*'
      - PolicyName: Logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: '*'
      - PolicyName: Glue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - glue:GetDatabase
            - glue:GetTable
            Resource: '*'
      - PolicyName: DDBGetPutScan
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchWriteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:GetShardIterator
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DescribeStream
            - dynamodb:UpdateTable
            - dynamodb:GetRecords
            Resource: '*'
  StartProcessing:
    Type: AWS::Serverless::Function
    Properties:
      Handler: startProcessing.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/746bd1b91ae1eb30ba3fbc8692438a7f
      Description: Initiates the Query Processing Step Function.
      MemorySize: 128
      Timeout: 300
      Policies:
      - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationHistoryTableName
      Environment:
        Variables:
          CURATION_DETAILS_TABLE_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
          CURATION_HISTORY_TABLE_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationHistoryTableName
          STEP_FUNCTION:
            Ref: QueryProcessor
          CURATION_BUCKET_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-S3Curation-Name
          FAILED_CURATION_BUCKET_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-S3FailedCuration-Name
          SCRIPTS_BUCKET_NAME:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-S3Scripts-Name
  RetrieveDetails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: retrieveDetails.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/6002eecb39ec3675ce9d1173b93d2285
      Description: Retrieves the details from the curation details dynamodb table.
      MemorySize: 128
      Timeout: 300
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
  ValidateDetails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: validateDetails.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/34750c6410e888d87247f76d455d2abe
      Description: Validates details that are within the dynamodb entry.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
  QueryProcessor:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName:
        Fn::Sub: ${EnvironmentPrefix}queryengine
      DefinitionString:
        Fn::Sub:
        - "{\n  \"Comment\": \"State machine to query data available in the data lake\"\
          ,\n  \"StartAt\": \"RetrieveDetails\",\n  \"States\": {\n    \"RetrieveDetails\"\
          : {\n      \"Type\": \"Task\",\n      \"Resource\": \"${RetrieveDetailsArn}\"\
          ,\n      \"Comment\": \"Retrieves the details that are within the dynamodb\
          \ entry.\",\n      \"Next\": \"ValidateDetails\",\n      \"Catch\": [\n\
          \          {\n             \"ErrorEquals\": [\"RetrieveCurationDetailsException\"\
          ,\"Exception\"],\n             \"ResultPath\": \"$.error-info\",\n     \
          \        \"Next\": \"FinishedProcessingUnsuccessfulFile\"\n          }\n\
          \       ],\n      \"Retry\" : [\n          {\n            \"ErrorEquals\"\
          : [\n              \"Lambda.Unknown\",\n              \"Lambda.ServiceException\"\
          ,\n              \"Lambda.AWSLambdaException\",\n              \"Lambda.SdkClientException\"\
          \n            ],\n            \"IntervalSeconds\": 2,\n            \"MaxAttempts\"\
          : 4,\n            \"BackoffRate\": 1.5\n          },\n          {\n    \
          \        \"ErrorEquals\": [\n              \"States.ALL\"\n            ],\n\
          \            \"IntervalSeconds\": 2,\n            \"MaxAttempts\": 4,\n\
          \            \"BackoffRate\": 1.5\n          }\n      ]\n\n    },\n    \"\
          ValidateDetails\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"\
          ${ValidateDetailsArn}\",\n      \"Comment\": \"Validates the details that\
          \ are within the dynamodb entry.\",\n      \"Next\": \"FinishedProcessingSuccessfulFile\"\
          ,\n      \"Catch\": [\n          {\n             \"ErrorEquals\": [\"RetrieveCurationDetailsException\"\
          ,\"Exception\"],\n             \"ResultPath\": \"$.error-info\",\n     \
          \        \"Next\": \"FinishedProcessingUnsuccessfulFile\"\n          }\n\
          \       ],\n      \"Retry\" : [\n          {\n            \"ErrorEquals\"\
          : [\n              \"Lambda.Unknown\",\n              \"Lambda.ServiceException\"\
          ,\n              \"Lambda.AWSLambdaException\",\n              \"Lambda.SdkClientException\"\
          \n            ],\n            \"IntervalSeconds\": 2,\n            \"MaxAttempts\"\
          : 4,\n            \"BackoffRate\": 1.5\n          },\n          {\n    \
          \        \"ErrorEquals\": [\n              \"States.ALL\"\n            ],\n\
          \            \"IntervalSeconds\": 2,\n            \"MaxAttempts\": 4,\n\
          \            \"BackoffRate\": 1.5\n          }\n      ]\n\n    },      \
          \                           \n    \"FinishedProcessingUnsuccessfulFile\"\
          : {\n      \"Type\": \"Pass\",\n      \"Result\": \"Fail\",\n      \"End\"\
          : true\n    },\n    \"FinishedProcessingSuccessfulFile\": {\n      \"Type\"\
          : \"Pass\",\n      \"Result\": \"Success\",\n      \"End\": true\n    }\n\
          \  }\n}"
        - RetrieveDetailsArn:
            Fn::GetAtt:
            - RetrieveDetails
            - Arn
          ValidateDetailsArn:
            Fn::GetAtt:
            - ValidateDetails
            - Arn
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
