AWSTemplateFormatVersion: 2010-09-09
Description: Creates the DynamoDB tables, S3 buckets and Code commit repository structure for the Accelerated Data Pipelines.
Parameters:
  # Prefix used for S3 Buckets and DynamomDB tables (so devo, gamma, prod etc can share account)
  EnvironmentPrefix:
    Type: String
    Description: Enter an environment prefix for the S3 Buckets and DynamoDB tables ([a-z][a-z0-9]+)
    MinLength: 3
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"
    
  ProjectName:
    Type: String
    Description: Enter an name for the project which is used for the S3 Buckets and DynamoDB tables ([a-z][a-z0-9]+)
    MinLength: 3
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"
  
  ProjectNamePrefix:
    Type: String
    Description: Enter an additional prefix to be appended before the project name to ensure the uniqueness of the S3 Buckets ([a-z][a-z0-9]+)
    MinLength: 2
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9]+"

  KMSKeyARN:
    Type: String
    Description: Enter a KMS Key ARN for the S3 bucket encryption (no encryption is applied if this field is blank).

  S3CurationName:
    Type: String
    Default: curation
    Description: Enter a name for the curation bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"

  CodeCommitScriptsName:
    Type: String
    Default: scripts
    Description: Enter the name of the codecommit repo for scripts.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"
  
  S3LogsName:
    Type: String
    Default: curation-logs
    Description: Enter the name of the S3 logs bucket.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "([a-zA-Z0-9]){1}([a-zA-Z0-9-])*"

  CurationDetailsTableName:
    Type: String
    Default: curationDetails
    Description: Enter the Curation Details DynamoDB table name.
  CurationHistoryTableName:
    Type: String
    Default: curationHistory
    Description: Enter the Curation History DynamoDB table name.

Conditions:
  HasKMSKey:
    !Not [!Equals [!Ref KMSKeyARN, ""]]

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Environment Prefix
        Parameters:
          - EnvironmentPrefix
      - Label:
          default: Project Name
        Parameters:
          - ProjectName
          - ProjectNamePrefix
      - Label:
          default: Code Commit Repository
        Parameters:
          - CodeCommitScriptsName
      - Label:
          default: S3 Data Buckets
        Parameters:
          - S3CurationName
          - S3LogsName
      - Label:
          default: KMS Keys
        Parameters:
          - KMSKeyARN
      - Label:
          default: Curation DynamoDB Table
        Parameters:
          - CurationDetailsTableName
          - CurationHistoryTableName
    
Resources:
  # DynamoDB Tables
  CurationDetailsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "curationType"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "curationType"
          KeyType: "HASH"
      SSESpecification:
          SSEEnabled: true
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      TableName: !Sub '${EnvironmentPrefix}${CurationDetailsTableName}'
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE      
  CurationHistoryTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "curationType"
          AttributeType: "S"
        -
          AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "curationType"
          KeyType: "HASH"
        -
          AttributeName: "timestamp"
          KeyType: "RANGE"
      SSESpecification:
          SSEEnabled: true
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      TableName: !Sub '${EnvironmentPrefix}${CurationHistoryTableName}'
      BillingMode: PAY_PER_REQUEST      
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  # S3 Buckets  
  AcceleratedQueryCodePackages:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-acceleratedquerycodepackages"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true            
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
          
  S3Logs:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: "LogDeliveryWrite"
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3LogsName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true              
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]

      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
  
  CodeCommitScriptsRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub "${EnvironmentPrefix}-${CodeCommitScriptsName}"
      RepositoryDescription: This is a repository to store the sql scripts used for curation
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName

  S3Curation:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Sub "${ProjectNamePrefix}${ProjectName}-${EnvironmentPrefix}-${S3CurationName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true   
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey,"aws:kms","AES256"]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyARN, !Ref "AWS::NoValue"]
      Tags: 
        - Key: "Environment"
          Value: !Ref EnvironmentPrefix
        - Key: "Project Name"
          Value: !Ref ProjectName
      LoggingConfiguration:
        DestinationBucketName: !Ref S3Logs
        LogFilePrefix:
          !Sub "${S3CurationName}/"
Outputs:
  CurationDetailsTableName:
    Description: The name of the Curation Details DDBTable
    Value: !Ref CurationDetailsTable
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationDetailsTableName"  
  CurationDetailsTableArn:
    Description: The ARN of the Curation Details DDBTable
    Value: !GetAtt CurationDetailsTable.Arn
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationDetailsTableARN"   
  CurationDetailsStreamArn:
    Description: The ARN of the Curation Details Stream
    Value: !GetAtt CurationDetailsTable.StreamArn
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationDetailsStreamARN"   
  CurationHistoryTableName:
    Description: The name of the Curation History DDBTable
    Value: !Ref CurationHistoryTable
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationHistoryTableName"          
  CurationHistoryStreamArn:
    Description: The ARN of the Curation History Stream
    Value: !GetAtt CurationHistoryTable.StreamArn
    Export:
      Name: !Sub "${EnvironmentPrefix}-CurationHistoryStreamARN" 
  S3CuratedName:
    Description: The name of the Curation S3 bucket created
    Value: !Ref S3Curation
    Export: 
      Name: !Sub "${EnvironmentPrefix}-S3Curation-Name"
  CodeCommitScriptsName:
    Description: The name of the codecommit repo created for scripts
    Value: !GetAtt CodeCommitScriptsRepo.Name
    Export: 
      Name: !Sub "${EnvironmentPrefix}-CodeCommitScriptsRepo-Name"
  CodeCommitScriptsCloneUrlHttp:
    Description: The cloneurl for the codecommit scripts repo
    Value: !GetAtt CodeCommitScriptsRepo.CloneUrlHttp
    Export: 
      Name: !Sub "${EnvironmentPrefix}-CodeCommitScriptsRepo-CloneUrlHttp"