AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates the Schedule Stream component of the Accelerated Data Pipeline
Parameters:
  EnvironmentPrefix:
    Type: String
    Description: Enter the environment prefix used for the schedule stream setup
    MinLength: 3
    MaxLength: 19
    AllowedPattern: '[a-z][a-z0-9-]+'
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${EnvironmentPrefix}-schedule-event-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: EventBridge
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:DeleteRule
            - events:DescribeRule
            - events:PutRule
            - events:PutTargets
            Resource: '*'
      - PolicyName: DynamoDBStreamSubscribe
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
            Resource:
              Fn::ImportValue:
                Fn::Sub: ${EnvironmentPrefix}-CurationDetailsStreamARN
      - PolicyName: CloudwatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: '*'
  CurationDetailsStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn:
        Fn::ImportValue:
          Fn::Sub: ${EnvironmentPrefix}-CurationDetailsStreamARN
      FunctionName:
        Fn::GetAtt:
        - CreateNewEventRule
        - Arn
      StartingPosition: LATEST
    DependsOn: LambdaExecutionRole
  CreateNewEventRule:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${EnvironmentPrefix}-create-new-event-rule
      Handler: createNewEventRule.lambda_handler
      Runtime: python3.6
      CodeUri: s3://tdfv1wadatahub-test-acceleratedquerycodepackages/9a05310bd04b05726e13cd2d79620087
      Description: Create a new event rule using the cron expression.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-CurationDetailsTableName
      Environment:
        Variables:
          START_CURATION_PROCESS_FUNCTION_ARN:
            Fn::ImportValue:
              Fn::Sub: ${EnvironmentPrefix}-StartCurationProcessFunctionArn
