AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Creates the Schedule Stream component of the Accelerated Data Pipeline

Parameters:
  EnvironmentPrefix:
    Type: String
    Description: Enter the environment prefix used for the schedule stream setup
    MinLength: 3
    MaxLength: 19
    AllowedPattern: "[a-z][a-z0-9-]+"
Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${EnvironmentPrefix}-accelerated-query-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: EventBridge
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:DeleteRule
                  - events:DescribeRule
                  - events:PutRule
                  - events:PutTargets
                Resource: "*"
  # DynamoDB Stream for Curation Table
  CurationDetailsStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1 # Trigger one lambda per document
      Enabled: True
      EventSourceArn: 
        Fn::ImportValue:
          !Sub "${EnvironmentPrefix}-CurationDetailsStreamARN"
      FunctionName: 
        Fn::GetAtt: [ CreateNewEventRule , Arn ]
      StartingPosition: LATEST # Subscribe from the tail of the stream
    DependsOn: LambdaExecutionRole
                
  # SAM Serverless (Lambda) functions
  CreateNewEventRule:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub "${EnvironmentPrefix}-create-new-event-rule"
      Handler: createNewEventRule.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/createNewEventRule.py
      Description: Create a new event rule using the cron expression.
      MemorySize: 128
      Timeout: 300
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Policies: 
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue:
                !Sub "${EnvironmentPrefix}-CurationDetailsTableName"